Don't register signal handlers if running on Windows (#35)
The following happens on Windows for HUP (for Apache Kafka):

[2017-10-11 21:45:11,642] FATAL (kafka.Kafka$)
java.lang.IllegalArgumentException: Unknown signal: HUP
at sun.misc.Signal.(Unknown Source)
at kafka.Kafka$.registerHandler$1(Kafka.scala:67)
at kafka.Kafka$.registerLoggingSignalHandler(Kafka.scala:73)
at kafka.Kafka$.main(Kafka.scala:82)
at kafka.Kafka.main(Kafka.scala)

I thought it was safer not to register them at all since the additional
logging is a nice to have and we haven't tested it on Windows.

Also see apache/kafka#4066.